CREATE PROCEDURE INSERTAR_ALUMNO
@NOMBRE_ALUM VARCHAR(40),
@APELLIDOS_ALUM VARCHAR(40),
@DNI_ALUM CHAR(8),
@SEMESTRE VARCHAR(15),
@ID_ESPECIALIDAD INT,
@TURNO_ALUM VARCHAR(15)
AS
BEGIN
	INSERT INTO ALUMNO VALUES (@NOMBRE_ALUM,@APELLIDOS_ALUM,@DNI_ALUM,@SEMESTRE,@ID_ESPECIALIDAD,@TURNO_ALUM)    
END