CREATE PROCEDURE INSERTAR_PRESTAMOS_COMPUTADORA
@ID_ALUMNO INT,
@ID_COMP INT,
@ID_ESPECIALIDAD INT,
@ID INT,
@HORA_ENTRADA TIME,
@TIEMPO INT,
@FECHA DATETIME,
@ESTADO VARCHAR(20)
AS
BEGIN
	INSERT INTO PRESTAMOS_COMPUTADORA VALUES (@ID_ALUMNO,@ID_COMP,@ID_ESPECIALIDAD,@ID,@HORA_ENTRADA,@TIEMPO,@FECHA,@ESTADO)
END